"""Reaction template knowledge base.

Each template is a fully-balanced specific reaction. Matching is exact on the
reactant formula multiset (plus optional catalysts/carriers); temperature gates
select whether a reaction is plausible under the given conditions.

Template fields:
  id           unique snake_case id
  name         human-readable description
  type         reaction class (for display / grouping)
  reactants    [[formula, coefficient], ...]
  products     [[formula, coefficient], ...]
  conditions   {min_temp, max_temp} in deg C (None = unbounded)
  optional     [formula, ...] species allowed alongside reactants but not consumed
  priority     higher number wins when several templates match
  notes        plain-language description of the reaction
"""

TEMPLATES = [
    # ============================ NEUTRALIZATION ============================
    {'id': 'hcl_naoh', 'name': 'Hydrochloric acid + sodium hydroxide',
     'type': 'neutralization', 'reactants': [['HCl', 1], ['NaOH', 1]], 'products': [['NaCl', 1], ['H2O', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Classic acid-base neutralization producing table salt and water.'},
    {'id': 'hcl_koh', 'name': 'Hydrochloric acid + potassium hydroxide',
     'type': 'neutralization', 'reactants': [['HCl', 1], ['KOH', 1]], 'products': [['KCl', 1], ['H2O', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Acid-base neutralization producing potassium chloride and water.'},
    {'id': 'hcl_caoh2', 'name': 'Hydrochloric acid + calcium hydroxide',
     'type': 'neutralization', 'reactants': [['HCl', 2], ['Ca(OH)2', 1]], 'products': [['CaCl2', 1], ['H2O', 2]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Acid-base neutralization producing calcium chloride and water.'},
    {'id': 'h2so4_naoh', 'name': 'Sulfuric acid + sodium hydroxide',
     'type': 'neutralization', 'reactants': [['H2SO4', 1], ['NaOH', 2]], 'products': [['Na2SO4', 1], ['H2O', 2]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Acid-base neutralization producing sodium sulfate and water.'},
    {'id': 'h2so4_koh', 'name': 'Sulfuric acid + potassium hydroxide',
     'type': 'neutralization', 'reactants': [['H2SO4', 1], ['KOH', 2]], 'products': [['K2SO4', 1], ['H2O', 2]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Acid-base neutralization producing potassium sulfate and water.'},
    {'id': 'hno3_naoh', 'name': 'Nitric acid + sodium hydroxide',
     'type': 'neutralization', 'reactants': [['HNO3', 1], ['NaOH', 1]], 'products': [['NaNO3', 1], ['H2O', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Acid-base neutralization producing sodium nitrate and water.'},
    {'id': 'hno3_koh', 'name': 'Nitric acid + potassium hydroxide',
     'type': 'neutralization', 'reactants': [['HNO3', 1], ['KOH', 1]], 'products': [['KNO3', 1], ['H2O', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Acid-base neutralization producing potassium nitrate and water.'},
    {'id': 'hno3_caoh2', 'name': 'Nitric acid + calcium hydroxide',
     'type': 'neutralization', 'reactants': [['HNO3', 2], ['Ca(OH)2', 1]], 'products': [['Ca(NO3)2', 1], ['H2O', 2]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Acid-base neutralization producing calcium nitrate and water.'},
    {'id': 'hcl_mgoh2', 'name': 'Hydrochloric acid + magnesium hydroxide',
     'type': 'neutralization', 'reactants': [['HCl', 2], ['Mg(OH)2', 1]], 'products': [['MgCl2', 1], ['H2O', 2]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Acid-base neutralization producing magnesium chloride and water.'},
    {'id': 'h2so4_mgoh2', 'name': 'Sulfuric acid + magnesium hydroxide',
     'type': 'neutralization', 'reactants': [['H2SO4', 1], ['Mg(OH)2', 1]], 'products': [['MgSO4', 1], ['H2O', 2]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Acid-base neutralization producing magnesium sulfate and water.'},
    {'id': 'hcl_aloh3', 'name': 'Hydrochloric acid + aluminum hydroxide',
     'type': 'neutralization', 'reactants': [['HCl', 3], ['Al(OH)3', 1]], 'products': [['AlCl3', 1], ['H2O', 3]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Acid-base neutralization producing aluminum chloride and water.'},
    {'id': 'hcl_baoh2', 'name': 'Hydrochloric acid + barium hydroxide',
     'type': 'neutralization', 'reactants': [['HCl', 2], ['Ba(OH)2', 1]], 'products': [['BaCl2', 1], ['H2O', 2]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Acid-base neutralization producing barium chloride and water.'},
    {'id': 'h2so4_baoh2', 'name': 'Sulfuric acid + barium hydroxide',
     'type': 'neutralization', 'reactants': [['H2SO4', 1], ['Ba(OH)2', 1]], 'products': [['BaSO4', 1], ['H2O', 2]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Acid-base neutralization producing an insoluble barium sulfate precipitate.'},
    {'id': 'ch3cooh_naoh', 'name': 'Acetic acid + sodium hydroxide',
     'type': 'neutralization', 'reactants': [['CH3COOH', 1], ['NaOH', 1]], 'products': [['CH3COONa', 1], ['H2O', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Acid-base neutralization producing sodium acetate and water.'},
    {'id': 'hno3_nh4oh', 'name': 'Nitric acid + ammonium hydroxide',
     'type': 'neutralization', 'reactants': [['HNO3', 1], ['NH4OH', 1]], 'products': [['NH4NO3', 1], ['H2O', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Acid-base neutralization producing ammonium nitrate and water.'},
    {'id': 'hcl_nh4oh', 'name': 'Hydrochloric acid + ammonium hydroxide',
     'type': 'neutralization', 'reactants': [['HCl', 1], ['NH4OH', 1]], 'products': [['NH4Cl', 1], ['H2O', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Acid-base neutralization producing ammonium chloride and water.'},
    {'id': 'h2so4_nh4oh', 'name': 'Sulfuric acid + ammonium hydroxide',
     'type': 'neutralization', 'reactants': [['H2SO4', 1], ['NH4OH', 2]], 'products': [['(NH4)2SO4', 1], ['H2O', 2]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Acid-base neutralization producing ammonium sulfate and water.'},
    {'id': 'h3po4_naoh', 'name': 'Phosphoric acid + sodium hydroxide',
     'type': 'neutralization', 'reactants': [['H3PO4', 1], ['NaOH', 3]], 'products': [['Na3PO4', 1], ['H2O', 3]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Acid-base neutralization producing trisodium phosphate and water.'},
    {'id': 'hcl_nh3', 'name': 'Hydrochloric acid + ammonia',
     'type': 'neutralization', 'reactants': [['HCl', 1], ['NH3', 1]], 'products': [['NH4Cl', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Ammonia gas reacts with HCl to form white ammonium chloride smoke.'},
    {'id': 'hno3_nh3', 'name': 'Nitric acid + ammonia',
     'type': 'neutralization', 'reactants': [['HNO3', 1], ['NH3', 1]], 'products': [['NH4NO3', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Ammonia reacts with nitric acid to form ammonium nitrate, a fertilizer and oxidizer.'},

    # ============================ ACID + CARBONATE ============================
    {'id': 'hcl_na2co3', 'name': 'Hydrochloric acid + sodium carbonate',
     'type': 'acid_carbonate', 'reactants': [['HCl', 2], ['Na2CO3', 1]], 'products': [['NaCl', 2], ['H2O', 1], ['CO2', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Effervescent reaction releasing carbon dioxide gas.'},
    {'id': 'h2so4_na2co3', 'name': 'Sulfuric acid + sodium carbonate',
     'type': 'acid_carbonate', 'reactants': [['H2SO4', 1], ['Na2CO3', 1]], 'products': [['Na2SO4', 1], ['H2O', 1], ['CO2', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Releases carbon dioxide gas and forms sodium sulfate.'},
    {'id': 'hcl_caco3', 'name': 'Hydrochloric acid + calcium carbonate',
     'type': 'acid_carbonate', 'reactants': [['HCl', 2], ['CaCO3', 1]], 'products': [['CaCl2', 1], ['H2O', 1], ['CO2', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Dissolves limestone/chalk with vigorous effervescence of CO2.'},
    {'id': 'hno3_caco3', 'name': 'Nitric acid + calcium carbonate',
     'type': 'acid_carbonate', 'reactants': [['HNO3', 2], ['CaCO3', 1]], 'products': [['Ca(NO3)2', 1], ['H2O', 1], ['CO2', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Releases carbon dioxide and forms soluble calcium nitrate.'},
    {'id': 'hcl_mgco3', 'name': 'Hydrochloric acid + magnesium carbonate',
     'type': 'acid_carbonate', 'reactants': [['HCl', 2], ['MgCO3', 1]], 'products': [['MgCl2', 1], ['H2O', 1], ['CO2', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Releases carbon dioxide and forms magnesium chloride.'},
    {'id': 'hcl_nahco3', 'name': 'Hydrochloric acid + sodium bicarbonate',
     'type': 'acid_carbonate', 'reactants': [['HCl', 1], ['NaHCO3', 1]], 'products': [['NaCl', 1], ['H2O', 1], ['CO2', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Baking soda fizzes: CO2 bubbles out immediately.'},
    {'id': 'hcl_k2co3', 'name': 'Hydrochloric acid + potassium carbonate',
     'type': 'acid_carbonate', 'reactants': [['HCl', 2], ['K2CO3', 1]], 'products': [['KCl', 2], ['H2O', 1], ['CO2', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Releases carbon dioxide and forms potassium chloride.'},
    {'id': 'ch3cooh_nahco3', 'name': 'Acetic acid + sodium bicarbonate',
     'type': 'acid_carbonate', 'reactants': [['CH3COOH', 1], ['NaHCO3', 1]], 'products': [['CH3COONa', 1], ['H2O', 1], ['CO2', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'The vinegar-and-baking-soda reaction: a fast CO2 fountain.'},

    # ============================ ACID + METAL ============================
    {'id': 'hcl_zn', 'name': 'Hydrochloric acid + zinc',
     'type': 'acid_metal', 'reactants': [['HCl', 2], ['Zn', 1]], 'products': [['ZnCl2', 1], ['H2', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Zinc dissolves producing hydrogen gas bubbles.'},
    {'id': 'h2so4_zn', 'name': 'Sulfuric acid + zinc',
     'type': 'acid_metal', 'reactants': [['H2SO4', 1], ['Zn', 1]], 'products': [['ZnSO4', 1], ['H2', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Zinc reacts with dilute sulfuric acid releasing hydrogen.'},
    {'id': 'hcl_fe', 'name': 'Hydrochloric acid + iron',
     'type': 'acid_metal', 'reactants': [['HCl', 2], ['Fe', 1]], 'products': [['FeCl2', 1], ['H2', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Iron reacts with HCl forming iron(II) chloride and hydrogen.'},
    {'id': 'h2so4_fe', 'name': 'Sulfuric acid + iron',
     'type': 'acid_metal', 'reactants': [['H2SO4', 1], ['Fe', 1]], 'products': [['FeSO4', 1], ['H2', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Iron forms pale-green iron(II) sulfate and hydrogen.'},
    {'id': 'hcl_mg', 'name': 'Hydrochloric acid + magnesium',
     'type': 'acid_metal', 'reactants': [['HCl', 2], ['Mg', 1]], 'products': [['MgCl2', 1], ['H2', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Vigorous reaction — magnesium ribbon dissolves rapidly with H2.'},
    {'id': 'h2so4_mg', 'name': 'Sulfuric acid + magnesium',
     'type': 'acid_metal', 'reactants': [['H2SO4', 1], ['Mg', 1]], 'products': [['MgSO4', 1], ['H2', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Magnesium dissolves forming magnesium sulfate and hydrogen.'},
    {'id': 'hcl_al', 'name': 'Hydrochloric acid + aluminum',
     'type': 'acid_metal', 'reactants': [['HCl', 6], ['Al', 2]], 'products': [['AlCl3', 2], ['H2', 3]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Aluminum reacts after its oxide skin is dissolved, forming AlCl3 and H2.'},
    {'id': 'hcl_ca', 'name': 'Hydrochloric acid + calcium',
     'type': 'acid_metal', 'reactants': [['HCl', 2], ['Ca', 1]], 'products': [['CaCl2', 1], ['H2', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Calcium reacts vigorously forming calcium chloride and hydrogen.'},
    {'id': 'hcl_ni', 'name': 'Hydrochloric acid + nickel',
     'type': 'acid_metal', 'reactants': [['HCl', 2], ['Ni', 1]], 'products': [['NiCl2', 1], ['H2', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Nickel dissolves slowly forming green nickel(II) chloride and hydrogen.'},
    {'id': 'hcl_sn', 'name': 'Hydrochloric acid + tin',
     'type': 'acid_metal', 'reactants': [['HCl', 2], ['Sn', 1]], 'products': [['SnCl2', 1], ['H2', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Tin reacts forming tin(II) chloride and hydrogen.'},
    {'id': 'hcl_pb', 'name': 'Hydrochloric acid + lead',
     'type': 'acid_metal', 'reactants': [['HCl', 2], ['Pb', 1]], 'products': [['PbCl2', 1], ['H2', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Lead reacts slowly because PbCl2 is only slightly soluble.'},

    # ============================ METAL + OXYGEN ============================
    {'id': 'na_o2', 'name': 'Sodium + oxygen',
     'type': 'metal_oxygen', 'reactants': [['Na', 4], ['O2', 1]], 'products': [['Na2O', 2]],
     'conditions': {'min_temp': 150, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Sodium burns with a yellow flame forming sodium oxide.'},
    {'id': 'k_o2', 'name': 'Potassium + oxygen',
     'type': 'metal_oxygen', 'reactants': [['K', 4], ['O2', 1]], 'products': [['K2O', 2]],
     'conditions': {'min_temp': 150, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Potassium burns with a lilac flame forming potassium oxide.'},
    {'id': 'ca_o2', 'name': 'Calcium + oxygen',
     'type': 'metal_oxygen', 'reactants': [['Ca', 2], ['O2', 1]], 'products': [['CaO', 2]],
     'conditions': {'min_temp': 300, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Calcium burns with a brick-red flame forming quicklime (CaO).'},
    {'id': 'mg_o2', 'name': 'Magnesium + oxygen',
     'type': 'metal_oxygen', 'reactants': [['Mg', 2], ['O2', 1]], 'products': [['MgO', 2]],
     'conditions': {'min_temp': 500, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Magnesium burns with a blinding white flame forming white MgO ash.'},
    {'id': 'al_o2', 'name': 'Aluminum + oxygen',
     'type': 'metal_oxygen', 'reactants': [['Al', 4], ['O2', 3]], 'products': [['Al2O3', 2]],
     'conditions': {'min_temp': 900, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Aluminum powder burns intensely (thermite chemistry) forming alumina.'},
    {'id': 'zn_o2', 'name': 'Zinc + oxygen',
     'type': 'metal_oxygen', 'reactants': [['Zn', 2], ['O2', 1]], 'products': [['ZnO', 2]],
     'conditions': {'min_temp': 800, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Zinc burns forming yellow-turning-white zinc oxide.'},
    {'id': 'fe_o2', 'name': 'Iron + oxygen',
     'type': 'metal_oxygen', 'reactants': [['Fe', 4], ['O2', 3]], 'products': [['Fe2O3', 2]],
     'conditions': {'min_temp': 900, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Iron rusting / burning forms reddish-brown iron(III) oxide.'},
    {'id': 'cu_o2', 'name': 'Copper + oxygen',
     'type': 'metal_oxygen', 'reactants': [['Cu', 2], ['O2', 1]], 'products': [['CuO', 2]],
     'conditions': {'min_temp': 400, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Copper tarnishes black as copper(II) oxide forms.'},
    {'id': 'li_o2', 'name': 'Lithium + oxygen',
     'type': 'metal_oxygen', 'reactants': [['Li', 4], ['O2', 1]], 'products': [['Li2O', 2]],
     'conditions': {'min_temp': 150, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Lithium burns with a crimson flame forming lithium oxide.'},

    # ============================ METAL + WATER ============================
    {'id': 'na_h2o', 'name': 'Sodium + water',
     'type': 'metal_water', 'reactants': [['Na', 2], ['H2O', 2]], 'products': [['NaOH', 2], ['H2', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 12,
     'notes': 'Sodium fizzes violently on water, releasing hydrogen that can ignite.'},
    {'id': 'k_h2o', 'name': 'Potassium + water',
     'type': 'metal_water', 'reactants': [['K', 2], ['H2O', 2]], 'products': [['KOH', 2], ['H2', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 12,
     'notes': 'Potassium reacts explosively — the released hydrogen ignites with a lilac flame.'},
    {'id': 'li_h2o', 'name': 'Lithium + water',
     'type': 'metal_water', 'reactants': [['Li', 2], ['H2O', 2]], 'products': [['LiOH', 2], ['H2', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 12,
     'notes': 'Lithium reacts steadily with water forming lithium hydroxide and hydrogen.'},
    {'id': 'ca_h2o', 'name': 'Calcium + water',
     'type': 'metal_water', 'reactants': [['Ca', 1], ['H2O', 2]], 'products': [['Ca(OH)2', 1], ['H2', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 12,
     'notes': 'Calcium bubbles in water forming milky calcium hydroxide and hydrogen.'},
    {'id': 'mg_h2o', 'name': 'Magnesium + water',
     'type': 'metal_water', 'reactants': [['Mg', 1], ['H2O', 2]], 'products': [['Mg(OH)2', 1], ['H2', 1]],
     'conditions': {'min_temp': 80, 'max_temp': None}, 'optional': [], 'priority': 12,
     'notes': 'Magnesium reacts only with hot water/steam, forming Mg(OH)2 and hydrogen.'},
    {'id': 'fe_h2o', 'name': 'Iron + steam',
     'type': 'metal_water', 'reactants': [['Fe', 3], ['H2O', 4]], 'products': [['Fe3O4', 1], ['H2', 4]],
     'conditions': {'min_temp': 600, 'max_temp': None}, 'optional': [], 'priority': 12,
     'notes': 'Red-hot iron reacts with steam forming black magnetic oxide and hydrogen.'},

    # ============================ SINGLE DISPLACEMENT ============================
    {'id': 'fe_cuso4', 'name': 'Iron + copper(II) sulfate',
     'type': 'single_displacement', 'reactants': [['Fe', 1], ['CuSO4', 1]], 'products': [['FeSO4', 1], ['Cu', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Iron is more reactive — it displaces copper, which plates out as a brown-red deposit.'},
    {'id': 'zn_cuso4', 'name': 'Zinc + copper(II) sulfate',
     'type': 'single_displacement', 'reactants': [['Zn', 1], ['CuSO4', 1]], 'products': [['ZnSO4', 1], ['Cu', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Zinc displaces copper from the blue solution, which fades as zinc dissolves.'},
    {'id': 'cu_agno3', 'name': 'Copper + silver nitrate',
     'type': 'single_displacement', 'reactants': [['Cu', 1], ['AgNO3', 2]], 'products': [['Cu(NO3)2', 1], ['Ag', 2]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Copper displaces silver, which crystallizes as a grey "silver tree".'},
    {'id': 'fe_cucl2', 'name': 'Iron + copper(II) chloride',
     'type': 'single_displacement', 'reactants': [['Fe', 1], ['CuCl2', 1]], 'products': [['FeCl2', 1], ['Cu', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Iron displaces copper from its chloride solution.'},
    {'id': 'zn_agno3', 'name': 'Zinc + silver nitrate',
     'type': 'single_displacement', 'reactants': [['Zn', 1], ['AgNO3', 2]], 'products': [['Zn(NO3)2', 1], ['Ag', 2]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Zinc displaces silver from solution.'},
    {'id': 'mg_cuso4', 'name': 'Magnesium + copper(II) sulfate',
     'type': 'single_displacement', 'reactants': [['Mg', 1], ['CuSO4', 1]], 'products': [['MgSO4', 1], ['Cu', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Magnesium vigorously displaces copper, which deposits on the surface.'},
    {'id': 'al_cuso4', 'name': 'Aluminum + copper(II) sulfate',
     'type': 'single_displacement', 'reactants': [['Al', 2], ['CuSO4', 3]], 'products': [['Al2(SO4)3', 1], ['Cu', 3]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Aluminum displaces copper forming aluminum sulfate.'},
    {'id': 'fe_agno3', 'name': 'Iron + silver nitrate',
     'type': 'single_displacement', 'reactants': [['Fe', 1], ['AgNO3', 2]], 'products': [['Fe(NO3)2', 1], ['Ag', 2]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Iron displaces silver from silver nitrate solution.'},
    {'id': 'zn_feso4', 'name': 'Zinc + iron(II) sulfate',
     'type': 'single_displacement', 'reactants': [['Zn', 1], ['FeSO4', 1]], 'products': [['ZnSO4', 1], ['Fe', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Zinc is more reactive than iron, displacing iron from solution.'},

    # ============================ COMBUSTION ============================
    {'id': 'ch4_o2', 'name': 'Methane combustion',
     'type': 'combustion', 'reactants': [['CH4', 1], ['O2', 2]], 'products': [['CO2', 1], ['H2O', 2]],
     'conditions': {'min_temp': 540, 'max_temp': None}, 'optional': [], 'priority': 15,
     'notes': 'Complete combustion of natural gas — a strongly exothermic blue flame.'},
    {'id': 'c2h6_o2', 'name': 'Ethane combustion',
     'type': 'combustion', 'reactants': [['C2H6', 2], ['O2', 7]], 'products': [['CO2', 4], ['H2O', 6]],
     'conditions': {'min_temp': 472, 'max_temp': None}, 'optional': [], 'priority': 15,
     'notes': 'Complete combustion of ethane.'},
    {'id': 'c3h8_o2', 'name': 'Propane combustion',
     'type': 'combustion', 'reactants': [['C3H8', 1], ['O2', 5]], 'products': [['CO2', 3], ['H2O', 4]],
     'conditions': {'min_temp': 470, 'max_temp': None}, 'optional': [], 'priority': 15,
     'notes': 'Complete combustion of LPG (propane) — fuel for grills and heaters.'},
    {'id': 'c4h10_o2', 'name': 'Butane combustion',
     'type': 'combustion', 'reactants': [['C4H10', 2], ['O2', 13]], 'products': [['CO2', 8], ['H2O', 10]],
     'conditions': {'min_temp': 405, 'max_temp': None}, 'optional': [], 'priority': 15,
     'notes': 'Complete combustion of butane — lighter fuel.'},
    {'id': 'c2h4_o2', 'name': 'Ethylene combustion',
     'type': 'combustion', 'reactants': [['C2H4', 1], ['O2', 3]], 'products': [['CO2', 2], ['H2O', 2]],
     'conditions': {'min_temp': 425, 'max_temp': None}, 'optional': [], 'priority': 15,
     'notes': 'Complete combustion of ethene.'},
    {'id': 'c2h5oh_o2', 'name': 'Ethanol combustion',
     'type': 'combustion', 'reactants': [['C2H5OH', 1], ['O2', 3]], 'products': [['CO2', 2], ['H2O', 3]],
     'conditions': {'min_temp': 365, 'max_temp': None}, 'optional': [], 'priority': 15,
     'notes': 'Complete combustion of ethanol — biofuel flame.'},
    {'id': 'c6h12o6_o2', 'name': 'Glucose combustion',
     'type': 'combustion', 'reactants': [['C6H12O6', 1], ['O2', 6]], 'products': [['CO2', 6], ['H2O', 6]],
     'conditions': {'min_temp': 200, 'max_temp': None}, 'optional': [], 'priority': 15,
     'notes': 'Combustion of glucose — the same net reaction as cellular respiration.'},
    {'id': 'c_o2', 'name': 'Carbon + oxygen',
     'type': 'combustion', 'reactants': [['C', 1], ['O2', 1]], 'products': [['CO2', 1]],
     'conditions': {'min_temp': 400, 'max_temp': None}, 'optional': [], 'priority': 15,
     'notes': 'Charcoal burns forming carbon dioxide.'},
    {'id': 'co_o2', 'name': 'Carbon monoxide + oxygen',
     'type': 'combustion', 'reactants': [['CO', 2], ['O2', 1]], 'products': [['CO2', 2]],
     'conditions': {'min_temp': 609, 'max_temp': None}, 'optional': [], 'priority': 15,
     'notes': 'Carbon monoxide burns with a blue flame to CO2.'},
    {'id': 'h2_o2', 'name': 'Hydrogen + oxygen',
     'type': 'combustion', 'reactants': [['H2', 2], ['O2', 1]], 'products': [['H2O', 2]],
     'conditions': {'min_temp': 500, 'max_temp': None}, 'optional': [], 'priority': 15,
     'notes': 'Oxyhydrogen — a clean, intensely hot flame producing only water.'},
    {'id': 's_o2', 'name': 'Sulfur + oxygen',
     'type': 'combustion', 'reactants': [['S', 1], ['O2', 1]], 'products': [['SO2', 1]],
     'conditions': {'min_temp': 190, 'max_temp': None}, 'optional': [], 'priority': 15,
     'notes': 'Sulfur burns with a blue flame producing pungent sulfur dioxide.'},
    {'id': 'h2s_o2', 'name': 'Hydrogen sulfide + oxygen',
     'type': 'combustion', 'reactants': [['H2S', 2], ['O2', 3]], 'products': [['SO2', 2], ['H2O', 2]],
     'conditions': {'min_temp': 260, 'max_temp': None}, 'optional': [], 'priority': 15,
     'notes': 'Burning rotten-egg gas forms SO2 and water.'},
    {'id': 'p_o2', 'name': 'Phosphorus + oxygen',
     'type': 'combustion', 'reactants': [['P', 4], ['O2', 5]], 'products': [['P2O5', 2]],
     'conditions': {'min_temp': 30, 'max_temp': None}, 'optional': [], 'priority': 15,
     'notes': 'White phosphorus ignites spontaneously in air forming P2O5 smoke.'},

    # ============================ SYNTHESIS ============================
    {'id': 'n2_h2', 'name': 'Nitrogen + hydrogen (Haber process)',
     'type': 'synthesis', 'reactants': [['N2', 1], ['H2', 3]], 'products': [['NH3', 2]],
     'conditions': {'min_temp': 450, 'max_temp': None}, 'optional': ['Fe'], 'priority': 10,
     'notes': 'Haber process: ammonia synthesis, industrially run at ~450 C with an iron catalyst.'},
    {'id': 'n2_o2', 'name': 'Nitrogen + oxygen',
     'type': 'synthesis', 'reactants': [['N2', 1], ['O2', 1]], 'products': [['NO', 2]],
     'conditions': {'min_temp': 2000, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'At lightning/furnace temperatures nitrogen and oxygen combine to nitric oxide.'},
    {'id': 'so2_o2', 'name': 'Sulfur dioxide + oxygen',
     'type': 'synthesis', 'reactants': [['SO2', 2], ['O2', 1]], 'products': [['SO3', 2]],
     'conditions': {'min_temp': 400, 'max_temp': None}, 'optional': ['Pt'], 'priority': 10,
     'notes': 'Contact-process step: SO2 is oxidized to SO3 over a platinum/vanadium catalyst.'},
    {'id': 'h2_cl2', 'name': 'Hydrogen + chlorine',
     'type': 'synthesis', 'reactants': [['H2', 1], ['Cl2', 1]], 'products': [['HCl', 2]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Hydrogen burns in chlorine forming hydrogen chloride gas.'},
    {'id': 'h2_br2', 'name': 'Hydrogen + bromine',
     'type': 'synthesis', 'reactants': [['H2', 1], ['Br2', 1]], 'products': [['HBr', 2]],
     'conditions': {'min_temp': 200, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Direct combination forming hydrogen bromide.'},
    {'id': 'na_cl2', 'name': 'Sodium + chlorine',
     'type': 'synthesis', 'reactants': [['Na', 2], ['Cl2', 1]], 'products': [['NaCl', 2]],
     'conditions': {'min_temp': 200, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Sodium burns in chlorine gas forming table salt.'},
    {'id': 'cao_h2o', 'name': 'Calcium oxide + water',
     'type': 'synthesis', 'reactants': [['CaO', 1], ['H2O', 1]], 'products': [['Ca(OH)2', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Slaking of lime: quicklime reacts exothermically with water.'},
    {'id': 'na2o_h2o', 'name': 'Sodium oxide + water',
     'type': 'synthesis', 'reactants': [['Na2O', 1], ['H2O', 1]], 'products': [['NaOH', 2]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Basic oxide dissolves to form sodium hydroxide.'},
    {'id': 'mgo_h2o', 'name': 'Magnesium oxide + water',
     'type': 'synthesis', 'reactants': [['MgO', 1], ['H2O', 1]], 'products': [['Mg(OH)2', 1]],
     'conditions': {'min_temp': 80, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Magnesium oxide reacts slowly with hot water to the hydroxide.'},
    {'id': 'co2_h2o', 'name': 'Carbon dioxide + water',
     'type': 'synthesis', 'reactants': [['CO2', 1], ['H2O', 1]], 'products': [['H2CO3', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'CO2 dissolving in water forms weak carbonic acid (fizzy drinks).'},
    {'id': 'so3_h2o', 'name': 'Sulfur trioxide + water',
     'type': 'synthesis', 'reactants': [['SO3', 1], ['H2O', 1]], 'products': [['H2SO4', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'SO3 reacts violently with water to make sulfuric acid.'},
    {'id': 'fe_s', 'name': 'Iron + sulfur',
     'type': 'synthesis', 'reactants': [['Fe', 1], ['S', 1]], 'products': [['FeS', 1]],
     'conditions': {'min_temp': 300, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Heated iron and sulfur combine to black iron(II) sulfide.'},

    # ============================ THERMAL DECOMPOSITION ============================
    {'id': 'caco3_decomp', 'name': 'Calcium carbonate decomposition',
     'type': 'decomposition', 'reactants': [['CaCO3', 1]], 'products': [['CaO', 1], ['CO2', 1]],
     'conditions': {'min_temp': 825, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Limestone is calcined to quicklime above ~825 C, driving off CO2.'},
    {'id': 'mgco3_decomp', 'name': 'Magnesium carbonate decomposition',
     'type': 'decomposition', 'reactants': [['MgCO3', 1]], 'products': [['MgO', 1], ['CO2', 1]],
     'conditions': {'min_temp': 350, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Magnesium carbonate decomposes to magnesium oxide and CO2 on heating.'},
    {'id': 'nahco3_decomp', 'name': 'Sodium bicarbonate decomposition',
     'type': 'decomposition', 'reactants': [['NaHCO3', 2]], 'products': [['Na2CO3', 1], ['H2O', 1], ['CO2', 1]],
     'conditions': {'min_temp': 150, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Baking soda in the oven releases CO2 (making baked goods rise).'},
    {'id': 'h2o2_decomp', 'name': 'Hydrogen peroxide decomposition',
     'type': 'decomposition', 'reactants': [['H2O2', 2]], 'products': [['H2O', 2], ['O2', 1]],
     'conditions': {'min_temp': 30, 'max_temp': None}, 'optional': ['MnO2'], 'priority': 10,
     'notes': 'H2O2 slowly breaks into water and oxygen; MnO2 catalyzes a rapid foam.'},
    {'id': 'caoh2_decomp', 'name': 'Calcium hydroxide decomposition',
     'type': 'decomposition', 'reactants': [['Ca(OH)2', 1]], 'products': [['CaO', 1], ['H2O', 1]],
     'conditions': {'min_temp': 580, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Slaked lime dehydrates to quicklime when strongly heated.'},
    {'id': 'mgoh2_decomp', 'name': 'Magnesium hydroxide decomposition',
     'type': 'decomposition', 'reactants': [['Mg(OH)2', 1]], 'products': [['MgO', 1], ['H2O', 1]],
     'conditions': {'min_temp': 350, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Magnesium hydroxide dehydrates to magnesium oxide.'},
    {'id': 'nh4cl_decomp', 'name': 'Ammonium chloride decomposition',
     'type': 'decomposition', 'reactants': [['NH4Cl', 1]], 'products': [['NH3', 1], ['HCl', 1]],
     'conditions': {'min_temp': 340, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Sublimation: NH4Cl dissociates into NH3 and HCl, recombining on cooling.'},
    {'id': 'nh4no3_decomp', 'name': 'Ammonium nitrate decomposition',
     'type': 'decomposition', 'reactants': [['NH4NO3', 1]], 'products': [['N2O', 1], ['H2O', 2]],
     'conditions': {'min_temp': 200, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Controlled heating yields laughing gas (N2O); uncontrolled heating detonates.'},
    {'id': 'kclo3_decomp', 'name': 'Potassium chlorate decomposition',
     'type': 'decomposition', 'reactants': [['KClO3', 2]], 'products': [['KCl', 2], ['O2', 3]],
     'conditions': {'min_temp': 150, 'max_temp': None}, 'optional': ['MnO2'], 'priority': 10,
     'notes': 'Heated KClO3 releases oxygen; MnO2 speeds it up. Classic oxygen-lab reaction.'},

    # ============================ ACID + METAL OXIDE ============================
    {'id': 'hcl_cuo', 'name': 'Hydrochloric acid + copper(II) oxide',
     'type': 'acid_oxide', 'reactants': [['HCl', 2], ['CuO', 1]], 'products': [['CuCl2', 1], ['H2O', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Black CuO dissolves to a blue-green copper chloride solution.'},
    {'id': 'h2so4_cuo', 'name': 'Sulfuric acid + copper(II) oxide',
     'type': 'acid_oxide', 'reactants': [['H2SO4', 1], ['CuO', 1]], 'products': [['CuSO4', 1], ['H2O', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Black CuO dissolves to a deep-blue copper sulfate solution.'},
    {'id': 'hno3_cuo', 'name': 'Nitric acid + copper(II) oxide',
     'type': 'acid_oxide', 'reactants': [['HNO3', 2], ['CuO', 1]], 'products': [['Cu(NO3)2', 1], ['H2O', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'CuO dissolves forming blue copper nitrate and water.'},
    {'id': 'hcl_fe2o3', 'name': 'Hydrochloric acid + iron(III) oxide',
     'type': 'acid_oxide', 'reactants': [['HCl', 6], ['Fe2O3', 1]], 'products': [['FeCl3', 2], ['H2O', 3]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Rust dissolves in acid to a yellow-brown iron(III) chloride solution.'},
    {'id': 'h2so4_fe2o3', 'name': 'Sulfuric acid + iron(III) oxide',
     'type': 'acid_oxide', 'reactants': [['H2SO4', 3], ['Fe2O3', 1]], 'products': [['Fe2(SO4)3', 1], ['H2O', 3]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Rust dissolves in sulfuric acid forming iron(III) sulfate.'},
    {'id': 'hcl_zno', 'name': 'Hydrochloric acid + zinc oxide',
     'type': 'acid_oxide', 'reactants': [['HCl', 2], ['ZnO', 1]], 'products': [['ZnCl2', 1], ['H2O', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'White ZnO dissolves forming zinc chloride and water.'},
    {'id': 'hcl_mgo', 'name': 'Hydrochloric acid + magnesium oxide',
     'type': 'acid_oxide', 'reactants': [['HCl', 2], ['MgO', 1]], 'products': [['MgCl2', 1], ['H2O', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'MgO neutralizes HCl forming magnesium chloride and water.'},
    {'id': 'h2so4_mgo', 'name': 'Sulfuric acid + magnesium oxide',
     'type': 'acid_oxide', 'reactants': [['H2SO4', 1], ['MgO', 1]], 'products': [['MgSO4', 1], ['H2O', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'MgO neutralizes H2SO4 forming magnesium sulfate and water.'},
    {'id': 'hcl_cao', 'name': 'Hydrochloric acid + calcium oxide',
     'type': 'acid_oxide', 'reactants': [['HCl', 2], ['CaO', 1]], 'products': [['CaCl2', 1], ['H2O', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Quicklime neutralizes HCl forming calcium chloride and water.'},
    {'id': 'hcl_al2o3', 'name': 'Hydrochloric acid + aluminum oxide',
     'type': 'acid_oxide', 'reactants': [['HCl', 6], ['Al2O3', 1]], 'products': [['AlCl3', 2], ['H2O', 3]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Alumina dissolves in acid forming aluminum chloride and water.'},

    # ============================ PRECIPITATION / DOUBLE DISPLACEMENT ============================
    {'id': 'agno3_nacl', 'name': 'Silver nitrate + sodium chloride',
     'type': 'precipitation', 'reactants': [['AgNO3', 1], ['NaCl', 1]], 'products': [['AgCl', 1], ['NaNO3', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'White curdy silver chloride precipitates immediately.'},
    {'id': 'agno3_kcl', 'name': 'Silver nitrate + potassium chloride',
     'type': 'precipitation', 'reactants': [['AgNO3', 1], ['KCl', 1]], 'products': [['AgCl', 1], ['KNO3', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'White silver chloride precipitate forms.'},
    {'id': 'bac l2_na2so4', 'name': 'Barium chloride + sodium sulfate',
     'type': 'precipitation', 'reactants': [['BaCl2', 1], ['Na2SO4', 1]], 'products': [['BaSO4', 1], ['NaCl', 2]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Dense white barium sulfate precipitate — the classic sulfate test.'},
    {'id': 'cuso4_naoh', 'name': 'Copper(II) sulfate + sodium hydroxide',
     'type': 'precipitation', 'reactants': [['CuSO4', 1], ['NaOH', 2]], 'products': [['Cu(OH)2', 1], ['Na2SO4', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Pale-blue gelatinous copper hydroxide precipitates.'},
    {'id': 'feso4_naoh', 'name': 'Iron(II) sulfate + sodium hydroxide',
     'type': 'precipitation', 'reactants': [['FeSO4', 1], ['NaOH', 2]], 'products': [['Fe(OH)2', 1], ['Na2SO4', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Dirty-green iron(II) hydroxide precipitates, darkening on air exposure.'},
    {'id': 'fecl3_naoh', 'name': 'Iron(III) chloride + sodium hydroxide',
     'type': 'precipitation', 'reactants': [['FeCl3', 1], ['NaOH', 3]], 'products': [['Fe(OH)3', 1], ['NaCl', 3]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Red-brown iron(III) hydroxide precipitates.'},
    {'id': 'mgso4_naoh', 'name': 'Magnesium sulfate + sodium hydroxide',
     'type': 'precipitation', 'reactants': [['MgSO4', 1], ['NaOH', 2]], 'products': [['Mg(OH)2', 1], ['Na2SO4', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'White magnesium hydroxide precipitates.'},
    {'id': 'znso4_naoh', 'name': 'Zinc sulfate + sodium hydroxide',
     'type': 'precipitation', 'reactants': [['ZnSO4', 1], ['NaOH', 2]], 'products': [['Zn(OH)2', 1], ['Na2SO4', 1]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'White zinc hydroxide precipitates; dissolves in excess NaOH (amphoteric).'},
    {'id': 'cacl2_na2co3', 'name': 'Calcium chloride + sodium carbonate',
     'type': 'precipitation', 'reactants': [['CaCl2', 1], ['Na2CO3', 1]], 'products': [['CaCO3', 1], ['NaCl', 2]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'White calcium carbonate precipitates (hard-water test).'},
    {'id': 'cucl2_naoh', 'name': 'Copper(II) chloride + sodium hydroxide',
     'type': 'precipitation', 'reactants': [['CuCl2', 1], ['NaOH', 2]], 'products': [['Cu(OH)2', 1], ['NaCl', 2]],
     'conditions': {'min_temp': None, 'max_temp': None}, 'optional': [], 'priority': 10,
     'notes': 'Blue copper hydroxide precipitates from the green chloride solution.'},
]


def get_template(template_id):
    for t in TEMPLATES:
        if t['id'] == template_id:
            return t
    return None


def templates_for_type(reaction_type):
    return [t for t in TEMPLATES if t['type'] == reaction_type]


def all_templates():
    return list(TEMPLATES)


def reaction_types():
    return sorted({t['type'] for t in TEMPLATES})